// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/cook_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/cook_service.go -destination=internal/mock/service/mock_cook_service.go -package=mock_service
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	dto "github.com/hadi-projects/go-react-starter/internal/dto"
	dto0 "github.com/hadi-projects/go-react-starter/internal/dto/default"
	gomock "go.uber.org/mock/gomock"
)

// MockCookService is a mock of CookService interface.
type MockCookService struct {
	ctrl     *gomock.Controller
	recorder *MockCookServiceMockRecorder
	isgomock struct{}
}

// MockCookServiceMockRecorder is the mock recorder for MockCookService.
type MockCookServiceMockRecorder struct {
	mock *MockCookService
}

// NewMockCookService creates a new mock instance.
func NewMockCookService(ctrl *gomock.Controller) *MockCookService {
	mock := &MockCookService{ctrl: ctrl}
	mock.recorder = &MockCookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookService) EXPECT() *MockCookServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCookService) Create(req dto.CreateCookRequest) (*dto.CookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", req)
	ret0, _ := ret[0].(*dto.CookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCookServiceMockRecorder) Create(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCookService)(nil).Create), req)
}

// Delete mocks base method.
func (m *MockCookService) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCookServiceMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCookService)(nil).Delete), id)
}

// GetAll mocks base method.
func (m *MockCookService) GetAll(pagination *dto0.PaginationRequest) (*dto0.PaginationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", pagination)
	ret0, _ := ret[0].(*dto0.PaginationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockCookServiceMockRecorder) GetAll(pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockCookService)(nil).GetAll), pagination)
}

// GetByID mocks base method.
func (m *MockCookService) GetByID(id uint) (*dto.CookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*dto.CookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCookServiceMockRecorder) GetByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCookService)(nil).GetByID), id)
}

// Update mocks base method.
func (m *MockCookService) Update(id uint, req dto.UpdateCookRequest) (*dto.CookResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, req)
	ret0, _ := ret[0].(*dto.CookResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCookServiceMockRecorder) Update(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCookService)(nil).Update), id, req)
}
