// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/cook_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/cook_repository.go -destination=internal/mock/repository/mock_cook_repository.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	dto "github.com/hadi-projects/go-react-starter/internal/dto/default"
	entity "github.com/hadi-projects/go-react-starter/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCookRepository is a mock of CookRepository interface.
type MockCookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCookRepositoryMockRecorder
	isgomock struct{}
}

// MockCookRepositoryMockRecorder is the mock recorder for MockCookRepository.
type MockCookRepositoryMockRecorder struct {
	mock *MockCookRepository
}

// NewMockCookRepository creates a new mock instance.
func NewMockCookRepository(ctrl *gomock.Controller) *MockCookRepository {
	mock := &MockCookRepository{ctrl: ctrl}
	mock.recorder = &MockCookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookRepository) EXPECT() *MockCookRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCookRepository) Create(arg0 *entity.Cook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCookRepositoryMockRecorder) Create(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCookRepository)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockCookRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCookRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCookRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockCookRepository) FindAll(pagination *dto.PaginationRequest) ([]entity.Cook, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", pagination)
	ret0, _ := ret[0].([]entity.Cook)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockCookRepositoryMockRecorder) FindAll(pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockCookRepository)(nil).FindAll), pagination)
}

// FindByID mocks base method.
func (m *MockCookRepository) FindByID(id uint) (*entity.Cook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Cook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCookRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCookRepository)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockCookRepository) Update(arg0 *entity.Cook) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCookRepositoryMockRecorder) Update(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCookRepository)(nil).Update), arg0)
}
